[dependencies]
glium = '0.27.0'
thiserror = '1.0.20'
vector2math = '0.9.0'

[dependencies.ttf-parser]
default-features = false
version = '0.8.2'

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'kule'
version = '0.1.0'
