[dependencies]
fontdue = '0.2.4'
glium = '0.27.0'
lyon_tessellation = '0.16.0'
thiserror = '1.0.20'
vector2math = '0.10.4'

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'kule'
version = '0.1.0'
